#!/bin/bash
repodir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dldir=$repodir/downloaded_materials
#
# Ubuntu packages
#
packagelist=./repo/packages_to_install
apt-get -y update
apt-get -y upgrade
apt-get -y install apt-utils
apt-get -y install wget
( xargs -a <(awk '! /^ *(#|$)/' "$packagelist") -r -- apt-get -y install ) &
#
# Download materials
#
mkdir -p $dldir
cd $dldir
downloadlist=$repodir/downloadurls
cat $downloadlist | xargs -iaap bash -c '(wget aap) & '
wait
#
# Locales (from https://github.com/tianon/docker-brew-debian/issues/45. Hope this works)
#
echo "LC_ALL=en_US.UTF-8" >> /etc/environment
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen en_US.UTF-8
#
# Python
#
ln -s /usr/bin/python3.5 /usr/local/bin/python
ln -s /usr/bin/pip3 /usr/local/bin/pip
hash -r
pip install --upgrade pip
pip install lxml
pip install pyyaml
pip install --upgrade git+https://github.com/ixa-ehu/pynaf.git pip install --upgrade requests
pip install networkx==1.11
pip install --upgrade kafnafparserpy
#
# Treetagger
#
mkdir /usr/local/treetagger
cd /usr/local/treetagger
mv $dldir/tree-tagger-linux-3.2.1.tar.gz .
mv $dldir/tagger-scripts.tar.gz .
mv $dldir/install-tagger.sh .
mv $dldir/dutch-par-linux-3.2-utf8.bin.gz.
mv $dldir/dutch-tagset.txt .
mv $dldir/dutch2-par-linux-3.2-utf8.bin.gz .
chmod 775 install-tagger.sh
./install-tagger.sh
chmod -R o+rx bin
chmod -R o+rx cmd
chmod -R o+rx doc
chmod -R o+rx lib
rm *.tar.gz
